import pyodbc
import json
import os


# Configurações do banco de dados
server = 'localhost'
database = 'TRB_WEB_PM_MIGUEL_CALMON'
username = 'sa'
password = '123456'

# Tabelas para backup
tabelas_para_backup = 'CEM_CEMITERIO ',	 'CEM_MEMBRO ',	 'CEM_NATIMORTO ',	 'CEM_SEPULTAMENTO_CAUSA ',	 'CEM_TIPO_OBITO ',	 'GER_AGENCIA ',	 'GER_ANO ',	 'GER_API_INT_CONFIG_CHAVE ',	 'GER_API_INT_CONFIRMACAO ',	 'GER_BAIRRO ',	 'GER_BANCO ',	 'GER_CARGO ',	 'GER_CATEGORIA ',	 'GER_CNAE ',	 'GER_CNAE_PORTE ',	 'GER_CNAE_PORTE_FAIXA ',	 'GER_CNAE_SECUNDARIO ',	 'GER_CONFIG_CTP ',	 'GER_DIRIGENTE ',	 'GER_END_PESSOA ',	 'GER_ENTIDADE ',	 'GER_FUNCIONARIO ',	 'GER_HORA ',	 'GER_INFO_PESSOA ',	 'GER_INFORMATIVO ',	 'GER_INSS ',	 'GER_INSS_ANO ',	 'GER_IRRF ',	 'GER_IRRF_ANO ',	 'GER_MEDIDA ',	 'GER_MES ',	 'GER_MUNICIPIO ',	 'GER_ORGAO ',	 'GER_PAIS ',	 'GER_PAIS_BACEN ',	 'GER_PARAMETROS ',	 'GER_PERGUNTA_RESPOSTA ',	 'GER_PESSOA ',	 'GER_PESSOA_FISICA ',	 'GER_PESSOA_JURIDICA ',	 'GER_PLANO_CONTAS_INSTITUICAO ',	 'GER_PLANO_DE_CONTAS ',	 'GER_PLANO_DE_CONTAS_CONTA_CONTABIL ',	 'GER_PLANO_DE_CONTAS_EVE_CTP_apagar ',	 'GER_PODER ',	 'GER_RODAPE ',	 'GER_SECRETARIA ',	 'GER_SENHA ',	 'GER_SISTEMAS ',	 'GER_SOCIO ',	 'GER_TIPO_DOCTS ',	 'GER_TIPO_LOGRADOURO ',	 'GER_UF ',	 'GER_UF_IBGE ',	 'GER_VERSAO ',	 'GER_VERSAO_ITEM ',	 'GER_VISTORIA_TIPO ',	 'TRB_ABRIR_EXERCICIO ',	 'TRB_ACAO_FISCAL_PRORROGACAO_TIPO ',	 'TRB_AGRUPAMENTO ',	 'TRB_ALINHAMENTO ',	 'TRB_ALVARA ',	 'TRB_ALVARA_ITEM ',	 'TRB_AREA ',	 'TRB_ASSINATURA ',	 'TRB_ATIVIDADE ',	 'TRB_ATIVIDADE_ALIQUOTA ',	 'TRB_ATIVIDADE_DIVERSA ',	 'TRB_ATIVIDADE_DIVERSA_FAIXA ',	 'TRB_ATIVIDADE_DIVERSA_TIPO_ACRESCIMO ',	 'TRB_ATIVIDADE_ESTATISTICA ',	 'TRB_ATIVIDADE_PESSOA ',	 'TRB_ATIVIDADE_PESSOA_TRANSF ',	 'TRB_ATIVIDADE_SECUNDARIA_ISS ',	 'TRB_ATIVIDADE_TFF ',	 'TRB_ATIVIDADE_TFF_FAIXA ',	 'TRB_ATIVIDADE_TIPO ',	 'TRB_ATIVIDADE_TLL ',	 'TRB_ATIVIDADE_TLL_FAIXA ',	 'TRB_ATIVIDADE_VISA ',	 'TRB_ATIVIDADE_VISA_FAIXA ',	 'TRB_BAIXA ',	 'TRB_BAIXA_BANCARIA ',	 'TRB_BAIXA_DEU_CERTO ',	 'TRB_BAIXA_PROCESSO ',	 'TRB_BARRACA_FAIXA_PESSOA ',	 'TRB_BARRACA_PESSOA ',	 'TRB_CARTORIO ',	 'TRB_CERTIDAO ',	 'TRB_CERTIDAO_ITEM ',	 'TRB_COBRANCA_AMIGAVEL ',	 'TRB_COBRANCA_AMIGAVEL_ITEM ',	 'TRB_COBRANCA_AMIGAVEL_LOTE ',	 'TRB_COBRANCA_AMIGAVEL_TIPO ',	 'TRB_COBRANCA_AMIGAVEL_TIPO_FILTRO ',	 'TRB_CONCESSIONARIA ',	 'TRB_CONCESSIONARIA_TIPO ',	 'TRB_CONFIGURACAO ',	 'TRB_CONSERVACAO ',	 'TRB_CONSTITUICAO ',	 'TRB_COR ',	 'TRB_CORRECAO_ANUAL ',	 'TRB_CORRECAO_MENSAL ',	 'TRB_DAM_POR_PERIODO ',	 'TRB_DECLARACAO ',	 'TRB_DELIMITACAO ',	 'TRB_DISTRITO ',	 'TRB_DIVIDA ',	 'TRB_DIVIDA_LANCAMENTO ',	 'TRB_DOC_CONSTITUICAO ',	 'TRB_DOCUMENTOS_FISCAIS_TIPO ',	 'TRB_EMPRESA ',	 'TRB_EMPRESA_CARACTERISTICA ',	 'TRB_EMPRESA_OBRAS ',	 'TRB_EMPRESA_OBSERVACAO ',	 'TRB_EMPRESA_PERMISSAO_ALVARA ',	 'TRB_EMPRESA_REGIME_ESPECIAL ',	 'TRB_EMPRESA_REGIME_TRIBUTACAO ',	 'TRB_EMPRESA_SIMPLES_NACIONAL ',	 'TRB_EMPRESA_WEBSERVICES ',	 'TRB_ENQUADRAMENTO ',	 'TRB_EQUIPAMENTO_ESPECIAL ',	 'TRB_EQUIPAMENTO_URBANO ',	 'TRB_ESPECIE_AQUISICAO ',	 'TRB_EVENTOS_EXP_SIMPLES_NACIONAL ',	 'TRB_EXIGIBILIDADE_ISS_TIPO ',	 'TRB_FAIXA_TRIBUTO ',	 'TRB_FECHAMENTO_EXERCICIO ',	 'TRB_FECHAMENTO_RECEITA ',	 'TRB_FORMULASQL ',	 'TRB_FROTA_FAIXA ',	 'TRB_FROTA_PERMISSAO ',	 'TRB_FROTA_PESSOA ',	 'TRB_FROTA_TIPO ',	 'TRB_GRUPO_ATIVIDADES ',	 'TRB_HIERARQUIA ',	 'TRB_HORARIO ',	 'TRB_IMOVEL ',	 'TRB_IMOVEL_AJUSTE_CONFRONTANTE ',	 'TRB_IMOVEL_BCI ',	 'TRB_IMOVEL_CARACTERISTICA ',	 'TRB_IMOVEL_IMAGEM ',	 'TRB_IMOVEL_ISENCAO ',	 'TRB_IMOVEL_ITEM_CARACTERISTICA ',	 'TRB_IMOVEL_LOCALIZACAO ',	 'TRB_IMOVEL_PONTUACAO ',	 'TRB_IMOVEL_RURAL ',	 'TRB_IMOVEL_TIPOLOGIA ',	 'TRB_IMOVEL_TRANSFERENCIA ',	 'TRB_IMPORTACAO_CONFIGURACAO ',	 'TRB_INCIDENCIA ',	 'TRB_IPTU ',	 'TRB_IPTU_ALIQUOTA ',	 'TRB_IPTU_ALIQUOTA_ITEM ',	 'TRB_IPTU_ARQUIVO_TIPO_CONF ',	 'TRB_IPTU_PONTUACAO ',	 'TRB_IPTU_SERIE ',	 'TRB_IPTU_SERIE_SIMULACAO ',	 'TRB_IPTU_SIMULACAO ',	 'TRB_IPTU_TAXA ',	 'TRB_ISS ',	 'TRB_ISS_SUBSTITUICAO ',	 'TRB_ISS_TAXA ',	 'TRB_ISS_TIPO_PROFISSIONAL ',	 'TRB_ISS_TIPO_PROFISSIONAL_FAI ',	 'TRB_ITEM_AGRUPAMENTO ',	 'TRB_ITEM_BAIXA_BANCARIA ',	 'TRB_ITEM_LIVRO_DIVIDA ',	 'TRB_ITEM_NOTA_FISCAL ',	 'TRB_ITEM_PARCELAMENTO ',	 'TRB_ITEM_RECEITA ',	 'TRB_ITEM_TRANSFERENCIA_CONTRIBUINTE ',	 'TRB_ITIV_NATUREZA_TRANSACAO ',	 'TRB_ITIV_TAXA ',	 'TRB_ITVI ',	 'TRB_JUROS_SELIC ',	 'TRB_JUROS_SELIC_ANO ',	 'TRB_JUROS_SUPER_SIMPLES ',	 'TRB_LANC_LOTE ',	 'TRB_LANCAMENTO ',	 'TRB_LANCAMENTO_CORRECAO_PARCELA ',	 'TRB_LANCAMENTO_GERA_DIVIDA ',	 'TRB_LANCAMENTO_SITUACAO_TIPO ',	 'TRB_LIVRO_DIVIDA ',	 'TRB_LIVRO_DIVIDA_CONFIGURACAO ',	 'TRB_LOGRADOURO ',	 'TRB_LOGRADOURO_BAIRRO ',	 'TRB_LOTEAMENTO ',	 'TRB_MODULO_SITUACAO ',	 'TRB_MOTIVO_DEVOLUCAO_IPTU ',	 'TRB_MOTIVO_ISENCAO ',	 'TRB_MULTA_MORA ',	 'TRB_MULTA_MORA_SS ',	 'TRB_NIVEL ',	 'TRB_NOME_POPULAR_LOGRADOURO ',	 'TRB_NOTA_FISCAL ',	 'TRB_NOTA_FISCAL_TAXA ',	 'TRB_OCUPACAO_LOTE ',	 'TRB_ORDEM_SERVICO_TIPO ',	 'TRB_ORGANIZACAO_JURIDICA ',	 'TRB_ORIGEM_ACAO_FISCAL ',	 'TRB_PADRAO_CONSTRUCAO ',	 'TRB_PARAMETRO ',	 'TRB_PARCELAMENTO ',	 'TRB_PARCELAMENTO_REATIVADO ',	 'TRB_PASSEIO_LARGURA ',	 'TRB_PASSEIO_PAVIMENTO ',	 'TRB_PATRIMONIO ',	 'TRB_PAVIMENTO ',	 'TRB_PEDOLOGIA ',	 'TRB_PGV_EDIFICACAO ',	 'TRB_PGV_TERRENO ',	 'TRB_PLANTAO_FISCAL ',	 'TRB_PORTE_EMPRESA ',	 'TRB_POSICAO_NORTE ',	 'TRB_POSICIONAMENTO ',	 'TRB_QUADRA ',	 'TRB_QUALIFICACAO_SOCIEDADE ',	 'TRB_RECEITA_DIVERSA ',	 'TRB_REFIS ',	 'TRB_REFIS_DESCONTO ',	 'TRB_REGIAO ',	 'TRB_REGIME_USO ',	 'TRB_REGIN_MUNICIPIO ',	 'TRB_REL_ARRECADACAO ',	 'TRB_RELATORIO_JAR ',	 'TRB_SENTIDO_TRAFEGO ',	 'TRB_SETOR ',	 'TRB_SISOBRA_SINPAS ',	 'TRB_SISOBRA_WEBSERVICES_CONFIG ',	 'TRB_SITUACAO_EDIFICACAO ',	 'TRB_SITUACAO_IMOVEL ',	 'TRB_SITUACAO_TERRENO ',	 'TRB_SPC_SERASA_MOTIVO ',	 'TRB_TAB_PARCELAMENTO_REFIS ',	 'TRB_TAF_DOCUMENTO ',	 'TRB_TAREFA ',	 'TRB_TERMO_ACAO_FISCAL_TIPO ',	 'TRB_TFF ',	 'TRB_TFF_NAO_PROCESSADO ',	 'TRB_TIPO_ACAO_FISCAL ',	 'TRB_TIPO_ALVARA ',	 'TRB_TIPO_ALVARA_BLOQUEIO ',	 'TRB_TIPO_ALVARA_RECEITA ',	 'TRB_TIPO_CALCULO_IPTU ',	 'TRB_TIPO_CERTIDAO ',	 'TRB_TIPO_CERTIDAO_BLOQUEIO ',	 'TRB_TIPO_CERTIDAO_MENSAGEM ',	 'TRB_TIPO_CERTIDAO_RECEITA ',	 'TRB_TIPO_CERTIDAO_SITUACAO ',	 'TRB_TIPO_COMBUSTIVEL ',	 'TRB_TIPO_CORRECAO ',	 'TRB_TIPO_DECLARACAO ',	 'TRB_TIPO_EDIFICACAO ',	 'TRB_TIPO_LANCAMENTO ',	 'TRB_TIPO_LOTEAMENTO ',	 'TRB_TIPO_MOEDA ',	 'TRB_TIPO_MOTIVO_BAIXA ',	 'TRB_TIPO_MULTA_INFRACAO ',	 'TRB_TIPO_OCOR_FISCAL ',	 'TRB_TIPO_PROPRIETARIO ',	 'TRB_TIPO_SITUACAO ',	 'TRB_TIPO_SOCIEDADE ',	 'TRB_TIPO_TRIBUTO ',	 'TRB_TIPO_VIA ',	 'TRB_TIPO_VL_VENAL_EDIFICACAO ',	 'TRB_TITULO_LOGRADOURO ',	 'TRB_TLL ',	 'TRB_TOPOGRAFIA ',	 'TRB_TRANSFERENCIA_CONTRIBUINTE ',	 'TRB_TRECHO_CEP ',	 'TRB_TRECHO_LOGRADOURO ',	 'TRB_TRIBUTO_SITUACAO ',	 'TRB_TRIBUTO_SITUACAO_MOTIVO ',	 'TRB_TRIBUTO_TAXA ',	 'TRB_UNIDADE ',	 'TRB_UTILIZACAO ',	 'TRB_VARIAVEL ',	 'TRB_VEICULO_MARCA ',	 'TRB_VEICULO_MODELO ',	 'TRB_VENCIMENTO ',	 'TRB_VENCIMENTO_RECEITA ',	 'TRB_VERSAO ',	 'TRB_VERSAO_SCRIPT ',	 'TRB_VISA ',	 'TRB_VISA_TAXA ',	 'TRB_ZONA '

# Diretório onde os backups em JSON serão salvos
diretorio_backup = 'C:/Freire/BKP'

# Criar o diretório de backup se ele não existir
if not os.path.exists(diretorio_backup):
    os.makedirs(diretorio_backup)

# Conexão com o banco de dados
conn = pyodbc.connect(
    f'DRIVER=SQL Server;'
    f'SERVER={server};'
    f'DATABASE={database};'
    f'UID={username};'
    f'PWD={password};'
)

# Realizar o backup das tabelas para JSON
for tabela in tabelas_para_backup:
    query = f'SELECT * FROM {tabela}'
    cursor = conn.cursor()
    cursor.execute(query)
    
    # Extrair colunas da tabela
    columns = [column[0] for column in cursor.description]
    
    # Ler os registros da tabela e salvar em formato JSON
    records = []
    for row in cursor.fetchall():
        record = {}
        for i in range(len(columns)):
            record[columns[i]] = row[i]
        records.append(record)
    
    # Salvar registros em um arquivo JSON
    backup_file_path = os.path.join(diretorio_backup, f'{tabela}.json')
    with open(backup_file_path, 'w', encoding='utf-8') as backup_file:
        json.dump(records, backup_file, indent=4, ensure_ascii=False, default=str)

    cursor.close()

# Encerrar a conexão com o banco de dados
conn.close()

print("Backup para JSON concluído.")


